/**
 * Short display names for the 97 HS chapters (2-digit codes). Chapter
 * boundaries and meanings are stable across HS revisions; BACI only ships
 * HS6-level descriptions, so these are curated here. Chapter 77 is reserved
 * by the HS standard and 98 is not used in BACI; 99 covers unspecified goods.
 */
export const HS_CHAPTERS: Record<string, string> = {
  "01": "Live animals",
  "02": "Meat & edible meat offal",
  "03": "Fish & crustaceans",
  "04": "Dairy, eggs & honey",
  "05": "Other products of animal origin",
  "06": "Live plants & cut flowers",
  "07": "Vegetables",
  "08": "Fruit & nuts",
  "09": "Coffee, tea, maté & spices",
  "10": "Cereals",
  "11": "Milling products, malt & starches",
  "12": "Oil seeds & oleaginous fruits",
  "13": "Lac, gums & resins",
  "14": "Vegetable plaiting materials",
  "15": "Animal & vegetable fats and oils",
  "16": "Preparations of meat & fish",
  "17": "Sugars & sugar confectionery",
  "18": "Cocoa & cocoa preparations",
  "19": "Preparations of cereals, flour & milk",
  "20": "Preparations of vegetables & fruit",
  "21": "Miscellaneous edible preparations",
  "22": "Beverages, spirits & vinegar",
  "23": "Food-industry residues & animal feed",
  "24": "Tobacco",
  "25": "Salt, sulphur, earths & stone",
  "26": "Ores, slag & ash",
  "27": "Mineral fuels & oils",
  "28": "Inorganic chemicals",
  "29": "Organic chemicals",
  "30": "Pharmaceutical products",
  "31": "Fertilisers",
  "32": "Tanning & dyeing extracts, pigments",
  "33": "Essential oils, perfumery & cosmetics",
  "34": "Soap & washing preparations",
  "35": "Albuminoids, starches & glues",
  "36": "Explosives & pyrotechnics",
  "37": "Photographic & cinematographic goods",
  "38": "Miscellaneous chemical products",
  "39": "Plastics",
  "40": "Rubber",
  "41": "Raw hides, skins & leather",
  "42": "Articles of leather",
  "43": "Furskins & artificial fur",
  "44": "Wood & articles of wood",
  "45": "Cork",
  "46": "Basketware & wickerwork",
  "47": "Pulp of wood",
  "48": "Paper & paperboard",
  "49": "Printed books & newspapers",
  "50": "Silk",
  "51": "Wool & fine animal hair",
  "52": "Cotton",
  "53": "Other vegetable textile fibres",
  "54": "Man-made filaments",
  "55": "Man-made staple fibres",
  "56": "Wadding, felt & nonwovens",
  "57": "Carpets",
  "58": "Special woven fabrics",
  "59": "Impregnated & coated fabrics",
  "60": "Knitted or crocheted fabrics",
  "61": "Apparel, knitted or crocheted",
  "62": "Apparel, not knitted",
  "63": "Other made-up textile articles",
  "64": "Footwear",
  "65": "Headgear",
  "66": "Umbrellas & walking-sticks",
  "67": "Prepared feathers & artificial flowers",
  "68": "Articles of stone, plaster & cement",
  "69": "Ceramic products",
  "70": "Glass & glassware",
  "71": "Precious stones & metals",
  "72": "Iron & steel",
  "73": "Articles of iron or steel",
  "74": "Copper",
  "75": "Nickel",
  "76": "Aluminium",
  "78": "Lead",
  "79": "Zinc",
  "80": "Tin",
  "81": "Other base metals & cermets",
  "82": "Tools & cutlery of base metal",
  "83": "Miscellaneous articles of base metal",
  "84": "Machinery & mechanical appliances",
  "85": "Electrical machinery & equipment",
  "86": "Railway locomotives & rolling stock",
  "87": "Vehicles",
  "88": "Aircraft & spacecraft",
  "89": "Ships & boats",
  "90": "Optical, medical & precision instruments",
  "91": "Clocks & watches",
  "92": "Musical instruments",
  "93": "Arms & ammunition",
  "94": "Furniture, lighting & prefab buildings",
  "95": "Toys, games & sports equipment",
  "96": "Miscellaneous manufactured articles",
  "97": "Works of art & antiques",
  "99": "Commodities not specified by kind",
};
